spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: postgres
    password: qwerty1,0*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update